### PR TITLE
고민상세화면 UI작성

### LINKED ISSUE #16: 고민 상세화면 UI 작성

### PR DESCRIPTION
**Pull request by rlsmd9**
**이슈 번호** : close #16

**작업 내용** :   고민상세화면 UI작성

### CODE REVIEW

**Comment by who-is-hu** [comment]
Can one of the admins verify this patch?

**Comment by rlsmd9** [comment]
Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-07 at 23 08 56

**Comment by rlsmd9** [comment]
Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-07 at 23 08 37

**Comment by rlsmd9** [comment]
Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-09 at 17 51 39

**Pull request merged**
