### PR TITLE
고민추가 UI 작성

### LINKED ISSUE #26: 고민 작성화면 UI 작성

### PR DESCRIPTION
**Pull request by rlsmd9**
**이슈 번호** : close #26

**작업 내용** :   고민 추가 UI 작성

### CODE REVIEW

**Comment by who-is-hu** [comment]
Can one of the admins verify this patch?

**Comment by rlsmd9** [comment]
Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-08 at 23 54 35

**Comment by rlsmd9** [comment]
Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-08 at 23 54 42

**Comment by rlsmd9** [comment]
Simulator Screen Shot - iPhone 11 Pro Max - 2021-07-08 at 23 55 30

**Pull request merged**
